trigger: none

pool:
  vmImage: windows-latest

variables:
  bkstrgrg: 'rg-terraform-state'
  bkstrg: 'stracctstate'
  bkcontainer: 'tfstate'
  bkstrgkey: 'devpipeline.terraform.tfstate'


stages:
  - stage: tfdestroy
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest' # Use a specific stable version for prod workloads so breaking changes from version updates won't affect specific pipelines.
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)\AzureDevOpsandTerraformPipelines'
              backendServiceArm: 'Terraform'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)\AzureDevOpsandTerraformPipelines'
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Terraform'
          - task: TerraformTaskV4@4
            displayName: destroy
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)\AzureDevOpsandTerraformPipelines'
              provider: 'azurerm'
              command: 'destroy'
              environmentServiceNameAzureRM: 'Terraform'
