trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgrg:
  bkstrg:
  bkcontainer:
  bkstrgkey: 'devpipeline.terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest' # Use a specific stable version for prod workloads so breaking changes from version updates won't affect specific pipelines.
              
